baseURL: https://www.agamemnon.net/
languageCode: en-gb
title: Agamemnon.net

# Book configuration
disableKinds:
  - taxonomy
  - term
disablePathToLower: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true # Needed for mermaid/katex shortcodes
  tableOfContents:
    startLevel: 1

module:
  imports:
    - path: 'github.com/alex-shpak/hugo-book'

params:
  BookComments: false
  BookSection: docs
  BookRepo: https://github.com/petercb/agamemnon.net
  BooKTheme: auto
